---
title: "Main"
author: "Pierre Barban"
date: "30/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.align='center')
```


```{r}
#Packages
library(httr)
library(jsonlite)
library(dplyr)
library(stringr)
library(tidyr)
library(zoo)
library(ggplot2)
library(lubridate)
library(maps)
library(ggmap)

```


```{r }

Starting.date = Sys.Date() %m+% months(-13)
Ending.date = Sys.Date()
n = as.numeric(difftime(as.Date(Ending.date),as.Date(Starting.date), units = c("days")))

seq = seq(as.Date(Starting.date), by = "day", length.out = n)
seq = str_replace_all(seq, "-", "%2F")
data_list <- list()
  for (i in seq) {
    res <- GET(paste0("https://opendata.paris.fr/api/records/1.0/search/?dataset=comptage-velo-donnees-compteurs&q=&rows=-1&facet=id_compteur&facet=nom_compteur&facet=id&facet=name&facet=date&facet=installation_date&refine.date=",i))
    data_list[[length(data_list)+1]] = fromJSON(rawToChar(res$content))[["records"]][["fields"]]
  }
data = do.call(rbind, data_list)

data = na.omit(data) 

bike.data = data %>%  mutate(datetime = substr(date,
                                               nchar(date)-5,
                                               nchar(date)),
  datetime = as.POSIXct(date,
                                                        format = "%Y-%m-%dT%H:%M:%S",
                                                        tz = "UTC"),
                            dateday =  as.Date(datetime, format = "%Y-%m-%d"),
  Installation = as.Date(installation_date, format = "%Y-%m-%d"))
  


```

```{r}
#Historical Data

data_list <- list()

for (i in 2018:2020){

dataURL <- paste0("https://opendata.paris.fr/api/datasets/1.0/comptage-velo-historique-donnees-compteurs/attachments/",i,"_comptage_velo_donnees_compteurs_csv_zip")

download.file(dataURL,paste0("file",i,".zip"), mode="wb")
unzip(paste0("file",i,".zip"))
data_list[[length(data_list)+1]] = read.csv2(list.files(pattern="*.csv"))

file.remove(list.files(pattern="*.csv"))
}
Historical.data = do.call(rbind, data_list)



```



```{r}
#Date and datetime config

Historical.data = Historical.data %>% mutate(datetime = substr(Date.et.heure.de.comptage, nchar(Date.et.heure.de.comptage)-5,nchar(Date.et.heure.de.comptage)),
  datetime = as.POSIXct(Date.et.heure.de.comptage,
                                                        format = "%Y-%m-%dT%H:%M:%S",
                                                        tz = "UTC"),
                            dateday =  as.Date(datetime, format = "%Y-%m-%d"),
  Installation = as.Date(Date.d.installation.du.site.de.comptage, format = "%Y-%m-%d"),
                         year = paste0("Y",format(datetime,"%Y")),
                         month = paste0("M",format(datetime,"%m")),
                         day = paste0("D",format(datetime,"%d")),
                         weekdays = weekdays(dateday),
                         TIME = paste0(month,"-",day))
```



```{r}
AllData1 = bike.data %>% 
  select(nom_compteur, sum_counts, Installation, datetime, dateday)

AllData = Historical.data %>% 
  select(Nom.du.compteur, Comptage.horaire, Installation, datetime, dateday) %>% 
  rename(sum_counts = Comptage.horaire,
         nom_compteur = Nom.du.compteur) %>% 
  rbind(AllData1) %>% 
  mutate(sum_counts = as.numeric(sum_counts))

saveRDS(AllData,'AllBikeData.rds')

AllData = readRDS('AllBikeData.rds')

p1 =AllData %>%  
  filter(Installation <= as.Date("2018-01-01")) %>% 
   group_by(dateday)%>% 
  na.omit() %>% 
   summarise(sum_counts = mean(sum_counts, na.rm = T)) %>% 
   ggplot() + geom_line(aes(x = dateday, y = sum_counts)) +
  geom_rect(aes(xmin=as.Date("2019-12-05"),xmax=as.Date("2020-01-17"),ymin=-Inf,ymax=Inf,fill="Public Transit Strike"),colour=NA) +
  geom_rect(aes(xmin=as.Date("2020-03-17"),xmax=as.Date("2020-05-11"),ymin=-Inf,ymax=Inf,fill="First Lockdown"),colour=NA) +
  geom_rect(aes(xmin=as.Date("2020-10-30"),xmax=as.Date("2020-12-15"),ymin=-Inf,ymax=Inf,fill="Second Lockdown"),colour=NA) +
  geom_rect(aes(xmin=as.Date("2021-01-16"),xmax=as.Date("2021-06-21"),ymin=-Inf,ymax=Inf,fill="Curfew/Confinements"),colour=NA) +
  geom_line(aes(x =dateday, y=sum_counts),colour='#06067a', size = 0.5)+ 
  ylab("") +
  xlab("") + 
  labs(title = "Average Number of Cyclists \nper Counting Monitor per Day", subtitle = "Paris, Jan. 2018 - July 2021") +
  theme_minimal() +
  theme(plot.title = element_text(face = "bold", size = 20),
        plot.subtitle = element_text(colour = "#595a5c", size = 16),
        legend.title = element_blank(),
        legend.text = element_text( size = 8),
        legend.position="top",
        axis.text=element_text(size=12),
        panel.background = element_rect(fill = "White", colour = "White"),
        plot.background = element_rect(fill = "White", colour = "White"))
p1
ggsave("ParisBikes.png",p1)


```
```{r}
library(maps)
library(ggmap)
data(world.cities)
force(world.cities)
PARIS <- world.cities %>% filter(name == "Paris" & country.etc == "France") %>%
  mutate(lat = as.numeric(lat), long = as.numeric(long))

coef = 0.1
Paris_borders <- c(bottom = PARIS$lat - coef*0.5,
                   top = PARIS$lat + coef*0.5,
                   left = PARIS$long - coef,
                   right = PARIS$long + coef)


map <- get_stamenmap(Paris_borders, zoom = 14, maptype = "toner-lite")

res = GET("https://parisdata.opendatasoft.com/api/records/1.0/search/?dataset=comptage-velo-compteurs&q=&facet=id_compteur&facet=nom_compteur&facet=id&facet=name&facet=installation_date&rows=-1")
CompteursData= fromJSON(rawToChar(res$content))[["records"]][["fields"]]%>% mutate(coordinates = sub("c\\(", "", coordinates),
                                   coordinates = sub("\\)", "", coordinates))%>% 
  na.omit() %>%
  separate(coordinates, c("Lat", "Lon"), sep = ", ")%>%
  mutate(Lon = as.numeric(Lon),
         Lat = as.numeric(Lat))


map = ggmap(map) +
  geom_point(data = CompteursData, aes(x = Lon, y = Lat), size = 2 , color = "#0373fc")+
  xlab("") +
  ylab("") +
  ggtitle("CCyclists Counting Monitors",subtitle =
            paste0("Paris ", as.character(round(mean(PARIS$lat),digits = 3))," N,", as.character(round(mean(PARIS$long),digits = 3))," E")) +
  theme(plot.title = element_text(face = "bold", size = 24),plot.subtitle =
          element_text(colour = "#595a5c"),legend.title = element_text(color =
                                                                         "#595a5c", size = 20),
        legend.text = element_text( size = 14))

ggsave("map.png", map)

```


```{r}
dataURL = "https://etalab.github.io/jours-feries-france-data/csv/jours_feries_metropole.csv"

download.file(dataURL,paste0("greve.csv"), mode="wb")

holidays = read.csv("greve.csv",encoding = "utf-8", sep = ",")

file.remove(list.files(pattern="*.csv"))


```



```{r}
TEST = Historical.data %>% 
  {if(year == "Y2020") filter(., dateday < as.Date("2020-01-06")) else .} 

"Y2020" ~ dateday < as.Date("2020-01-06"))
"Y2021" ~ dateday < as.Date("2021-01-04")))
"Y2019" ~ dateday < as.Date("2019-01-07"),
"Y2018" ~ dateday < as.Date("2018-01-01")))
         
         




```







```{r setup, include=FALSE}








setwd("/Volumes/Files/Paris_Paper/")
velo.raw.data.2018 = read.csv("2018_comptage-velo-donnees-compteurs.csv", sep = ";")
velo.raw.data.2019 = read.csv("2019_comptage-velo-donnees-compteurs-2.csv", sep = ";")
velo.raw.data.2020 = read.csv("comptage-velo-donnees-compteurs.csv", sep = ";")

velo.raw.data = rbind(velo.raw.data.2018, velo.raw.data.2019, velo.raw.data.2020)

velo.raw.data$datetime = str_replace_all(velo.raw.data$Date.et.heure.de.comptage,"T", " ")
velo.raw.data$datetime = substr(velo.raw.data$date,1,19)
velo.raw.data$datetime = as.POSIXct(velo.raw.data$datetime, format = "%Y-%m-%d %H:%M:%S")
velo.raw.data$date = as.Date(format(velo.raw.data$datetime, format = "%Y-%m-%d"))
velo.raw.data$hour = as.numeric(format(velo.raw.data$datetime,"%H"))
velo.raw.data$day = as.numeric(format(velo.raw.data$datetime,"%d"))
velo.raw.data$month = as.numeric(format(velo.raw.data$datetime,"%m"))
velo.raw.data$year = as.numeric(format(velo.raw.data$datetime,"%Y"))
velo.raw.data$weekdays = as.numeric(as.POSIXlt(velo.raw.data$datetime)$wday )
velo.raw.data$week = as.numeric(format(velo.raw.data$datetime,"%V"))

velo.raw.data  = velo.raw.data  %>% distinct()

velo.raw.data$Comptage.horaire = as.numeric(velo.raw.data$Comptage.horaire)

#date d'installation 
names(velo.raw.data)[names(velo.raw.data) == "Date.d.installation.du.site.de.comptage"] <- "installation"
velo.raw.data$installation = as.Date(velo.raw.data$installation, format = "%Y-%m-%d")
velo.raw.data = velo.raw.data[velo.raw.data$installation <= as.Date("2019-01-01", format = "%Y-%m-%d"),]


min <- as.Date("2018-1-1")
max <- NA

p <- ggplot(velo.raw.data.Combined, aes(x=date, y=mean_q)) +
  geom_line(color="#69b3a2", size=0.5, alpha=0.9) + 
  xlab("") + 
  scale_x_date(limits = c(min, max))
p

```
